Auto add valtools
phuse-org/valtools pull request #158
Opened 2021-05-18 23:47 UTC by thebioengineer

Automatically add {valtools} to suggests for packages that use valtools::vt_use_config.

For packages that create the validation report have required packages for template to run put into "suggests" as well.

2021-05-18 23:47 UTC, thebioengineer commented
Shoot, meant to open as draft. disregard until I add tests.

2021-05-19 00:11 UTC, thebioengineer commented
@mariev - okay, I added some basic tests. The failures are due to texlive 😬 not the tests failing

2021-05-19 16:31 UTC, mariev requested changes
{valtools} needs to be added to Imports, not Suggests,

This is due to custom roxygen2 tags.

2021-05-20 22:00 UTC, mariev approved these changes

2021-05-20 23:16 UTC, merged