Include add_before and add_after in new item functions
phuse-org/valtools pull request #91
Opened 2021-04-08 02:35 UTC by elimillera

This PR adds the `add_file_to_config` functionality and adds the parameters `add_before` and `add_after` to be passed into the `before` and `after` parameters of `add_file_to_config`.

I'm not sure what the plans are for merging things in but I can start working off this branch to add 'tidy_select' functionality if I'm on the right track.

2021-04-08 14:46 UTC, thebioengineer requested changes
Good with the concept, but if you could go back and clean up the `pkg` argument, I think this PR will pass CI and be good to merge in. Hopefully that is quick enough!

2021-04-08 14:46 UTC, thebioengineer commented on R/code.R
> +vt_use_test_code <- function(name, username = vt_username(), open = interactive(), pkg = ".",
In the develop version of the package, `pkg` for all the vt_use_* functions is no longer necessary. you can remove that argument from these functions and from `vt_add_file_to_config()`.

2021-04-08 14:46 UTC, thebioengineer commented on R/code.R
> +  vt_add_file_to_config(filename = name, pkg = pkg, after = add_after,
`pkg` is no longer an argument in `vt_add_file_to_config()`, which is probably why the test is failing CI.

2021-04-08 14:46 UTC, thebioengineer commented on R/case.R
> +#' @param pkg Top-level of package
remove this line

2021-04-09 20:23 UTC, thebioengineer commented
there are tests failing now that were explicitly adding the files into the validation.yml! haha. at least we know if works!!

2021-04-09 20:24 UTC, elimillera commented
Yep! I'm working on those now. Should be ready by end of today

2021-04-10 23:22 UTC, elimillera commented
Hey @thebioengineer, I had some trouble with the tests. I think my VM must have a weird pdf render because I get a lot of errors on my machine. But they are passing here so it should be good to merge for now.

2021-04-12 19:16 UTC, mariev commented
@elimillera did pulling branch `develop` address the pdf build errors on your side? we are temporarily blocked from gh-actions due to https://github.com/r-lib/actions/issues/280 but no errors when I run devtools::check locally

2021-04-12 23:52 UTC, mariev approved these changes

2021-04-13 16:02 UTC, merged